apiVersion: v1
kind: Service
metadata:
  name: lexis-nexis-service
  namespace: lexis-nexis
spec:
  selector:
    app: rest-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
